# Default initial positions for scara_description's ros2_control fake system

initial_positions:
  joint1: 0.0
  joint2: 1.7977
  joint3: 2.618
  joint4: -1.5708
  joint5: 0.0
  joint6: 0.0
  joint7: 1.5708