/scara_motor_driver:
  ros__parameters:

    joint_count: 7
    joints:  ['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6', 'joint7']
    motors:  ['J1',     'J2',     'J3',     'J4',     'J5',     'J6',     'J7']
    offsets: [0.0,       -1.28,    -2.71,    1.571,    0.0,      0.0,      -1.571]
    ratios:  [973.4,     1.0,      1.0,      20.0,     20.0,     20.0,     108.0]